on:
  push:
    branches:
      - develop

name: Tests

jobs:
  tests:
    runs-on: self-hosted
    steps:
    # checkout branch
    - uses: actions/checkout@master
    - run: python -m venv ./venv
    - run: |
        source ./venv/bin/activate
        pip install --upgrade black flake8 isort
        make test
