on:
  push:
    branches:
      - develop

name: self-hosted-example

jobs:
  simpleExample:
    runs-on: self-hosted
    steps:
    # checkout branch
    - uses: actions/checkout@master
    - run: pip install --upgrade black flake8 isort
    - run: make test
